'use client';

import React from 'react';
import { FileBarChart, Plus } from 'lucide-react';
import { PageHeader } from '@/components/superAdmin/ui/PageHeader';
import { FilterBar } from '@/components/superAdmin/ui/FilterBar';
import { StatusBadge } from '@/components/superAdmin/ui/StatusBadge';
import { RowActionsMenu } from '@/components/superAdmin/ui/RowActionsMenu';
import { EmptyState } from '@/components/superAdmin/ui/EmptyState';
import { DataTable } from '@/components/admin/ui/DataTable';
import { useTableControls } from '@/lib/superAdmin/useTableControls';
import { mockReports } from '@/lib/superAdmin/mockData';

export const ReportsTable: React.FC = () => {
  const { query, setQuery, paged } = useTableControls({ rows: mockReports, searchFields: (r) => [r.name, r.type, r.generatedBy], pageSize: 20 });

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Generated platform reports."
        action={
          <button
            type="button"
            disabled
            title="Report generation is not implemented yet"
            className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-md text-xs font-bold bg-slate-200 text-slate-500 cursor-not-allowed"
          >
            <Plus className="w-3.5 h-3.5" />
            Generate Report
          </button>
        }
      />

      <FilterBar query={query} onQueryChange={setQuery} placeholder="Search by report name, type, or author…" />

      <div className="rounded-lg border border-slate-200 bg-white p-4 sm:p-5">
        {mockReports.length === 0 ? (
          <EmptyState icon={FileBarChart} title="No reports generated yet." />
        ) : (
          <DataTable
            rows={paged}
            rowKey={(r) => r.id}
            emptyLabel="No reports match your search."
            columns={[
              { key: 'name', header: 'Report', render: (r) => <p className="font-semibold text-slate-900">{r.name}</p> },
              { key: 'type', header: 'Type', render: (r) => r.type },
              { key: 'range', header: 'Range', render: (r) => <span className="text-slate-400">{r.range}</span> },
              { key: 'generatedBy', header: 'Generated By', render: (r) => r.generatedBy },
              { key: 'generatedAt', header: 'Date', render: (r) => <span className="text-slate-400">{r.generatedAt}</span> },
              { key: 'status', header: 'Status', render: (r) => <StatusBadge status={r.status} /> },
              {
                key: 'actions',
                header: '',
                align: 'right',
                render: () => <RowActionsMenu actions={[{ label: 'View', onClick: () => {} }, { label: 'Download', onClick: () => {} }]} />,
              },
            ]}
          />
        )}
      </div>
    </div>
  );
};
